package com.getrentbd.getrent.helper;

public class LocationList {

    public static String[] loacationList = new String[]{
            "Select Anyone",
            "Nnarayangang",
            "Konabari",
            "Shodorghat",
            "Islampur",
            "Adabor",
            "Badda",
            "Bagerhat",
            "Bangshal",
            "Banani",
            "Bandarban",
            "Barguna",
            "Barisal",
            "Bhasan Tek",
            "Bhatara",
            "Bhola",
            "Biman Bandar",
            "Airport",
            "Bogra",
            "Brahmanbaria",
            "Cantonment",
            "Chak Bazar",
            "Chadpur",
            "Chapai Nababgan",
            "Chittagong",
            "Chuadanga",
            "Comilla",
            "Cox's Bazar",
            "Dakshinkhan",
            "Darus Salam",
            "Demra",
            "Dhamri",
            "Dhanmodi",
            "Dinajpur",
            "Dohra",
            "Faridpur",
            "Feni",
            "Ggibandha",
            "Gazipur",
            "Gendaria",
            "Gopalganj",
            "Gulshan-1",
            "Gulshan-2",
            "Habiganj",
            "Hazaribagh",
            "Jhalokati",
            "Jamalpur",
            "Jatrabari",
            "Jessore",
            "Jhenaidah",
            "Joypurhat",
            "KAFRUL",
            "KADAMTALI",
            "KALABAGAN",
            "KAMRANGIR CHAR",
            "KERANIGANJ",
            "KHAGRACHHARI",
            "KHILGAON",
            "KHILKHET",
            "KHULNA",
            "KISHOREGONJ",
            "KOTWALI",
            "KUSHTIA",
            "KURIGRAM",
            "LALBAGH",
            "LALMONIRHAT",
            "LAKSHMIPUR",
            "MADARIPUR",
            "MAGURA",
            "MANIKGANJ",
            "MAULVIBAZAR",
            "MEHERPUR",
            "MIRPUR",
            "MOHAMMADPUR",
            "MOTIJHEEL",
            "MUGDA PARA",
            "MUNSHIGANJ",
            "MYMENSING",
            "NAOGAON",
            "NARSINGDI",
            "NARAIL",
            "NATORE",
            "NAWABGANJ",
            "NETRAKONA",
            "NEW MARKET",
            "NILPHAMARI",
            "NOAKHALI",
            "PABNA",
            "PALLABI",
            "PALTAN",
            "PANCHAGARH",
            "PATUAKHALI",
            "PIROJPUR",
            "RAJSHAHI",
            "RAMNA",
            "RAMPURA",
            "RANGAMATI",
            "RANGPUR",
            "SABUJBAGH",
            "RAJBARI",
            "SIRAJGANJ",
            "RUPNAGAR",
            "SAVAR",
            "SATKHIRA",
            "SHAHJAHANPUR",
            "SHAH ALI",
            "SHAHBAGH",
            "SHARIATPUR",
            "SHERPUR",
            "SHYAMPUR",
            "SHER-E-BANGLA NAGAR",
            "SUNAMGANJ",
            "SUTRAPUR",
            "SYLHET",
            "TANGAIL",
            "TEJGAON",
            "TEJGAON IND.AREA",
            "THAKURGAON",
            "TURAG",
            "UTTARA PASCHIM",
            "UTTARA PURBA",
            "UTTAR KHAN",
            "WARI",

    };
}
